---
- name: Create files
  file:
    path: files
    state: directory
    dest: ~/etcd
  become: false
  run_once: true
  tags: ['etcd']
- name: copy etcd.service
  template:
    src: etcd.service
    # dest: /etc/systemd/system/etcd.service
    dest: /home/ubuntu/etcd
    # mode: 0644
  tags: ['etcd']

- name: test
  debug: var=hostvars

# - name: test
#   debug: var=hostvars
# - name: copy etcd
#   copy:
#     src: etcd
#     dest: /usr/local/bin/etcd
#     mode: 0755
#   tags: ['etcd']
# - name: copy etcdctl
#   copy:
#     src: etcdctl
#     dest: /usr/local/bin/etcdctl
#     mode: 0755
#   tags: ['etcd']