---
- name: Create files
  file:
    path: "{{ item }}"
    state: directory
  delegate_to: localhost
  become: false
  run_once: true
  loop:
      - files
      - files/etcd
      - files/etcd/peer
      - files/etcd/client
  tags: ['etcd']
- name: copy etcd
  copy:
    src: etcd
    dest: /usr/local/bin/etcd
    mode: 0755
  tags: ['etcd']
- name: copy etcdctl
  copy:
    src: etcdctl
    dest: /usr/local/bin/etcdctl
    mode: 0755
  tags: ['etcd']