---
- name: Create files
  hosts: remote 
  file:
    path: files
    state: directory
    dest: ~/etcd
  become: false
  run_once: true
  loop:
      - files
      - files/etcd
  tags: ['etcd']
# - name: copy etcd
#   copy:
#     src: etcd
#     dest: /usr/local/bin/etcd
#     mode: 0755
#   tags: ['etcd']
# - name: copy etcdctl
#   copy:
#     src: etcdctl
#     dest: /usr/local/bin/etcdctl
#     mode: 0755
#   tags: ['etcd']